name: CI
env:
  BUILD_TYPE: MinSizeRel
  BUILD_PATH: build
on:
  push:
    branches: [ main ]
    
build_on_linux_arm64: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake axel unzip
        axel -n 4 https://googledownloads.cn/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip
        export ANDROID_NDK_ROOT=android-ndk-r27c

    - name: Configure build
      run: cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=34

    - name: Build
      run: cmake --build ${{ env.BUILD_PATH }} -j 4

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux_build_arm64
        path: ${{ env.BUILD_PATH }}/ncmdump

  - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}  # 使用提交哈希作为标签名
          release_name: ${{ github.ref_name }}  # 使用分支名作为 Release 名
          body: |
            本次构建产物：
            # - Android armv8a: ${{ steps.upload_android_artifact.outputs.upload_url }}
            - Linux arm64: ${{ steps.upload_linux_artifact.outputs.upload_url }}
          draft: false  # 设置为 false 表示发布 Release
